version: '3.8'

volumes:
  web-node-modules:

services:
  web:
    build: ./web
    volumes:
      - ./web:/app              # your source code
      - web-node-modules:/app/node_modules
    ports:
      - "3000:3000"
    environment: 
      - NEXT_PUBLIC_API_URL=http://localhost:8000 
    depends_on: 
      - api 
 
  api: 
    build: ./backend 
    volumes: 
      - ./backend:/app 
    ports: 
      - "8000:8000" 
