name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: echo "✅ Toolchains ready"

      - run: docker build -t ethicspressure:test .
      - run: pip install -r backend/requirements-dev.txt
      - run: mypy backend/app
      - run: ruff backend/app
      - run: cd web && npm install && npm run lint
